### ISSUE TITLE
Default WKND React SPA is not working

### ISSUE THREAD

**Issue by VitorTheGreat** [AdobeDocs/experience-manager-learn.pt-BR#1]
Issue in ./help/headless-tutorial/spa-editor/react/create-project.md

I followed step by step the documentation on how to start a **react spa project** but I couldn't see or use the default Text component and when checking the templates I see that the one used as default does not contains the component, I tried to use the Remote SPA Page template, that contains the Text component, but got a blank page and also no components to use. Is there any useful tutorial on how to implement React or Angular in AEM?

Thank you very much!

**Comment by yanlicao** [comment]
Dear @VitorTheGreat , thanks for sending us the feedback, we are following up with learning team to check this issue. If there is any update, we will get back to you. 
Cheers,

**Comment by yanlicao** [comment]
Dear @VitorTheGreat , can you try out whats outlined in:

https://github.com/AdobeDocs/experience-manager-learn.en/issues/85#issuecomment-1282568444

**Comment by yanlicao** [comment]
Dear @VitorTheGreat , we have not received a response and so will close this ticket. If you continue to experience the issue, please open a new ticket.
